; ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ ENEMY/OBJECT AI Data Tables						   บ
; ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
; บ  									   บ
; บ 									   บ
; ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ



;EQUATES

CHANCE_ALWAYS		EQU	$00
CHANCE_1in2		EQU	$01
CHANCE_1in4		EQU	$03
CHANCE_1in8		EQU	$07
CHANCE_1in16		EQU	$0F
CHANCE_1in32		EQU	$1F
CHANCE_1in64		EQU	$3F
CHANCE_1in128		EQU	$7F
CHANCE_1in256		EQU	$FF
EMPTY			EQU	0

			include	rapbot.ai
			include	snprbot.ai
			include	waspbot.ai

