; GLOBAL Lable Variables for GARGOYLES Genesis.

			GLOBAL	music_flg
			GLOBAL	TheStart

			GLOBAL	SegaLogoCHR		
			GLOBAL	DisneyLogoCHR		
			GLOBAL	DisneyLogoMAP		
			GLOBAL	DisneyLogoPAL		
			GLOBAL	TitlePageCHR		
			GLOBAL	TitlePageMAP		
			GLOBAL	TitlePagePAL		
			GLOBAL	Font8x8CHR		
			GLOBAL	ScratchChr1
			GLOBAL	ScratchChr2
			GLOBAL	ScratchChr3
			GLOBAL	ScratchChr4
		
			GLOBAL	CAnimDL1		
		
			GLOBAL	LevelData		
		
			GLOBAL	AnimData		

			GLOBAL	The_End			
			GLOBAL	BinLength		
			
			GLOBAL	Lev11ChrA
			GLOBAL	Lev11BlkA
			GLOBAL	Lev11MapA
			GLOBAL	Lev11MapB
			GLOBAL	Lev11Flr	
			GLOBAL	Lev11Con	
			GLOBAL	Lev11DATA

			GLOBAL	Lev12ChrA
			GLOBAL	Lev12BlkA
			GLOBAL	Lev12MapA
			GLOBAL	Lev12MapB
			GLOBAL	Lev12Flr	
			GLOBAL	Lev12Con	
			GLOBAL	Lev12DATA

			GLOBAL	Lev13ChrA
			GLOBAL	Lev13BlkA
			GLOBAL	Lev13MapA
			GLOBAL	Lev13MapB
			GLOBAL	Lev13Flr	
			GLOBAL	Lev13Con	
			GLOBAL	Lev13DATA

			GLOBAL	Lev14ChrA
			GLOBAL	Lev14BlkA
			GLOBAL	Lev14MapA
			GLOBAL	Lev14MapB
			GLOBAL	Lev14Flr	
			GLOBAL	Lev14Con	
			GLOBAL	Lev14DATA

			GLOBAL	Lev21ChrA
			GLOBAL	Lev21BlkA
			GLOBAL	Lev21MapA
			GLOBAL	Lev21MapB
			GLOBAL	Lev21Flr	
			GLOBAL	Lev21Con	
			GLOBAL	Lev21DATA

			GLOBAL	Lev22ChrA
			GLOBAL	Lev22BlkA
			GLOBAL	Lev22MapA
			GLOBAL	Lev22MapB
			GLOBAL	Lev22Flr	
			GLOBAL	Lev22Con	
			GLOBAL	Lev22DATA

			GLOBAL	Lev23ChrA
			GLOBAL	Lev23BlkA
			GLOBAL	Lev23MapA
			GLOBAL	Lev23MapB
			GLOBAL	Lev23Flr	
			GLOBAL	Lev23Con	
			GLOBAL	Lev23DATA

			GLOBAL	Lev24ChrA
			GLOBAL	Lev24BlkA
			GLOBAL	Lev24MapA
			GLOBAL	Lev24MapB
			GLOBAL	Lev24Flr	
			GLOBAL	Lev24Con	
			GLOBAL	Lev24DATA

			GLOBAL	Lev31ChrA
			GLOBAL	Lev31BlkA
			GLOBAL	Lev31MapA
			GLOBAL	Lev31MapB
			GLOBAL	Lev31Flr	
			GLOBAL	Lev31Con	
			GLOBAL	Lev31DATA

			GLOBAL	Lev32ChrA
			GLOBAL	Lev32BlkA
			GLOBAL	Lev32MapA
			GLOBAL	Lev32MapB
			GLOBAL	Lev32Flr	
			GLOBAL	Lev32Con	
			GLOBAL	Lev32DATA

			GLOBAL	Lev33ChrA
			GLOBAL	Lev33BlkA
			GLOBAL	Lev33MapA
			GLOBAL	Lev33MapB
			GLOBAL	Lev33Flr	
			GLOBAL	Lev33Con	
			GLOBAL	Lev33DATA

			GLOBAL	Lev34ChrA
			GLOBAL	Lev34BlkA
			GLOBAL	Lev34MapA
			GLOBAL	Lev34MapB
			GLOBAL	Lev34Flr	
			GLOBAL	Lev34Con	
			GLOBAL	Lev34DATA

			GLOBAL	Lev41ChrA
			GLOBAL	Lev41BlkA
			GLOBAL	Lev41MapA
			GLOBAL	Lev41MapB
			GLOBAL	Lev41Flr	
			GLOBAL	Lev41Con	
			GLOBAL	Lev41DATA

			GLOBAL	Lev42ChrA
			GLOBAL	Lev42BlkA
			GLOBAL	Lev42MapA
			GLOBAL	Lev42MapB
			GLOBAL	Lev42Flr	
			GLOBAL	Lev42Con	
			GLOBAL	Lev42DATA

			GLOBAL	Lev43ChrA
			GLOBAL	Lev43BlkA
			GLOBAL	Lev43MapA
			GLOBAL	Lev43MapB
			GLOBAL	Lev43Flr	
			GLOBAL	Lev43Con	
			GLOBAL	Lev43DATA

			GLOBAL	Lev44ChrA
			GLOBAL	Lev44BlkA
			GLOBAL	Lev44MapA
			GLOBAL	Lev44MapB
			GLOBAL	Lev44Flr	
			GLOBAL	Lev44Con	
			GLOBAL	Lev44DATA

			GLOBAL	Lev51ChrA
			GLOBAL	Lev51BlkA
			GLOBAL	Lev51MapA
			GLOBAL	Lev51MapB
			GLOBAL	Lev51Flr	
			GLOBAL	Lev51Con	
			GLOBAL	Lev51DATA

			GLOBAL	Lev61ChrA
			GLOBAL	Lev61BlkA
			GLOBAL	Lev61MapA
			GLOBAL	Lev61MapB
			GLOBAL	Lev61Flr	
			GLOBAL	Lev61Con	
			GLOBAL	Lev61DATA

			GLOBAL	Lev62ChrA
			GLOBAL	Lev62BlkA
			GLOBAL	Lev62MapA
			GLOBAL	Lev62MapB
			GLOBAL	Lev62Flr	
			GLOBAL	Lev62Con	
			GLOBAL	Lev62DATA

			GLOBAL	Lev63ChrA
			GLOBAL	Lev63BlkA
			GLOBAL	Lev63MapA
			GLOBAL	Lev63MapB
			GLOBAL	Lev63Flr	
			GLOBAL	Lev63Con	
			GLOBAL	Lev63DATA

			GLOBAL	Lev64ChrA
			GLOBAL	Lev64BlkA
			GLOBAL	Lev64MapA
			GLOBAL	Lev64MapB
			GLOBAL	Lev64Flr	
			GLOBAL	Lev64Con	
			GLOBAL	Lev64DATA

			GLOBAL	Lev71ChrA
			GLOBAL	Lev71BlkA
			GLOBAL	Lev71MapA
			GLOBAL	Lev71MapB
			GLOBAL	Lev71Flr	
			GLOBAL	Lev71Con	
			GLOBAL	Lev71DATA

			GLOBAL	Lev72ChrA
			GLOBAL	Lev72BlkA
			GLOBAL	Lev72MapA
			GLOBAL	Lev72MapB
			GLOBAL	Lev72Flr	
			GLOBAL	Lev72Con	
			GLOBAL	Lev72DATA

			GLOBAL	Lev73ChrA
			GLOBAL	Lev73BlkA
			GLOBAL	Lev73MapA
			GLOBAL	Lev73MapB
			GLOBAL	Lev73Flr	
			GLOBAL	Lev73Con	
			GLOBAL	Lev73DATA

			GLOBAL	Lev74ChrA
			GLOBAL	Lev74BlkA
			GLOBAL	Lev74MapA
			GLOBAL	Lev74MapB
			GLOBAL	Lev74Flr	
			GLOBAL	Lev74Con	
			GLOBAL	Lev74DATA

			GLOBAL	Lev99ChrA
			GLOBAL	Lev99BlkA
			GLOBAL	Lev99MapA
			GLOBAL	Lev99Flr 
			GLOBAL	Lev99Con 
			GLOBAL	Lev99Pal 
			GLOBAL	Lev99DATA

			GLOBAL	GolChr1			
			GLOBAL	GolChr2			
			GLOBAL	GolChr3a		
			GLOBAL	GolChr3b		
			GLOBAL	GolChr3c		
			GLOBAL	GolChr4			
			GLOBAL	GolChr5			
			GLOBAL	GolChr6			
			GLOBAL	GolChr7			
			GLOBAL	GolChr8			
			GLOBAL	GolChr9			
			GLOBAL	GolChr10		
			GLOBAL	GolChr11		
			GLOBAL	GolChr12		
			GLOBAL	GolChr13		
			GLOBAL	GolChr14		
			GLOBAL	GolChr15		
			GLOBAL	GolChr16		
			GLOBAL	GolChr17		
			GLOBAL	GolChr18		
			GLOBAL	GolChr19		
			GLOBAL	GolChr20		
			GLOBAL	GolChr21		
			GLOBAL	GolChr22		
			GLOBAL	GolChr23		
			GLOBAL	GolChr24		
			GLOBAL	GolChr25		
			GLOBAL	GolChr26		
			GLOBAL	GolChr27		
			GLOBAL	GolChr28		
			GLOBAL	GolChr29		
			GLOBAL	GolChr30		
			GLOBAL	GolChr31		
			GLOBAL	GolChr32		
			GLOBAL	GolChr33		
			GLOBAL	GolChr34		
			GLOBAL	GolChr35		
			GLOBAL	GolChr36		
			GLOBAL	GolChr37		
			GLOBAL	GolChr38		
			GLOBAL	GolChr39		
			GLOBAL	GolChr40		
			GLOBAL	GolChr41		
			GLOBAL	GolChr42		
			GLOBAL	GolChr43		
			GLOBAL	GolChr44		
			GLOBAL	GolChr45		
			GLOBAL	GolChr46		
			GLOBAL	GolChr47		
;			GLOBAL	;GolChr48		
;			GLOBAL	;GolChr49		
			GLOBAL	GolChr50		
			GLOBAL	GolChr51		
			GLOBAL	GolChr52		
			GLOBAL	GolChr53		
			GLOBAL	GolChr54		
			GLOBAL	GolChr55		
			GLOBAL	GolChr72		
			GLOBAL	GolChr73		
			GLOBAL	GolChr74		
			GLOBAL	GolChr77		
			GLOBAL	GolChr98		
			GLOBAL	GolChr99		
		
			GLOBAL	Health1Chr		
			GLOBAL	Health2Chr		
			GLOBAL	NumeralChr
			GLOBAL	IconChr

			GLOBAL	StrawmanChr		
			GLOBAL	StrawmanInc		
			GLOBAL	StrawmanOut		

			GLOBAL	L1M1FNL0_DATA		

			GLOBAL	RapChr1	
			GLOBAL	RapChr2	
			GLOBAL	RapChr3	
			GLOBAL	RapChr4	
			GLOBAL	RapChr5	
			GLOBAL	RapChr6	
			GLOBAL	RapChr7	
			GLOBAL	RapChr8	
			GLOBAL	RapChr9
			GLOBAL	RapChr10
			GLOBAL	RapChr11
			GLOBAL	RapChr12

			GLOBAL	CornerChr

			GLOBAL	BigExpChr1					
			GLOBAL	BigExpChr2
			GLOBAL	SmallExpChr1	
			GLOBAL	FireBallChr1	
			GLOBAL	FireBallChr2	
			GLOBAL	FireBallChr3	
			GLOBAL	FireBallChr4	
			GLOBAL	GlassChr1	
			GLOBAL	GlassChr2	
			GLOBAL	GlassChr3	
			GLOBAL	HorElecChr1	
			GLOBAL	VerElecChr1	
			GLOBAL	SparkChr1	
			GLOBAL	SparksChr1	
			GLOBAL	Sparks2Chr1	
			GLOBAL	MetalChr1	
			GLOBAL	MetalChr2	
			GLOBAL	MetalChr3	
			GLOBAL	MetalChr4	
			GLOBAL	MetalChr5	
			GLOBAL	MetalChr6	
			
			GLOBAL	SunSetChr1

			GLOBAL	SniChr1	
			GLOBAL	SniChr2a
			GLOBAL	SniChr2b
			GLOBAL	SniChr3a
			GLOBAL	SniChr3b
			GLOBAL	SniChr3c
			GLOBAL	SniChr3d
			GLOBAL	SniChr3e
			GLOBAL	SniChr4	
			GLOBAL	SniChr5	
			GLOBAL	SniChr6	
			GLOBAL	SniChr7	
			GLOBAL	SniChr8	
			
			GLOBAL	WaspChr1	
			GLOBAL	WaspChr3	
			GLOBAL	WaspChr4	
			GLOBAL	WaspChr5	
			GLOBAL	WaspChr6	
			GLOBAL	WaspChr7	
			GLOBAL	WaspChr8	
			GLOBAL	WaspChr9	
			GLOBAL	WaspChr10
			GLOBAL	WaspChr11
			
			GLOBAL	SpiChr1	
			GLOBAL	SpiChr2	
			GLOBAL	SpiChr3	
			GLOBAL	SpiChr4	
			GLOBAL	SpiChr5	
			GLOBAL	SpiChr6	
			GLOBAL	SpiChr7	
			GLOBAL	SpiChr8	
			GLOBAL	SpiChr9	
			GLOBAL	SpiChr10
			GLOBAL	SpiChr11
			GLOBAL	SpiChr12
			GLOBAL	SpiChr13
			GLOBAL	SpiChr14
			GLOBAL	SpiChr15
			GLOBAL	SpiChr16
			GLOBAL	SpiChr17
			GLOBAL	SpiChr18

			GLOBAL	TriloBotChr1
			GLOBAL	TriloBotChr2
			GLOBAL	TriloBotChr3
			GLOBAL	TriloBotChr4
			GLOBAL	TriloBotChr5
			GLOBAL	TriloBotChr6
			GLOBAL	TriloBotChr8
			GLOBAL	TriloBotChr9
			GLOBAL	TriloBotChr10
			GLOBAL	TriloBotChr11
			GLOBAL	TriloBotChr12
			GLOBAL	TriloBotChr13
			GLOBAL	OrbChr1

			GLOBAL	PiecePaperChr1
			GLOBAL	SkyLightChr1	
			GLOBAL	BreakLightChr1
			GLOBAL	BreakPipeChr1	
			GLOBAL	ThrowCrateChr1
			GLOBAL	WoodDebrisChr1
			GLOBAL	WoodDebrisChr2
			GLOBAL	WoodDebrisChr3
			GLOBAL	PigeonCoopChr1
			GLOBAL	PigeonChr1	
			GLOBAL	BreakEdgeLChr1
			GLOBAL	BreakEdgeRChr1
			GLOBAL	WallOverChr1	
			GLOBAL	WallDebrisChr1

			GLOBAL	gemsdmastart
			GLOBAL	gemsdmaend
			GLOBAL	gemsholdz80
			GLOBAL	gemsreleasez80
			GLOBAL	gemsloadz80
			GLOBAL	gemsstartz80
			GLOBAL	gemsputcbyte
			GLOBAL	gemsputptr
			GLOBAL	gemsinit
			GLOBAL	gemsstartsong
			GLOBAL	gemsstopsong
			GLOBAL	gemssettempo
			GLOBAL	gemspauseall
			GLOBAL	gemsresumeall
			GLOBAL	gemsstopall
			GLOBAL	gemslockchannel
			GLOBAL	gemsunlockchannel
			GLOBAL	gemsprogchange
			GLOBAL	gemsnoteon
			GLOBAL	gemsnoteoff
			GLOBAL	gemssetprio
			GLOBAL	gemspitchbend
			GLOBAL	gemssetenv
			GLOBAL	gemsretrigenv
			GLOBAL	gemssustain
			GLOBAL	gemsmute
			GLOBAL	gemsstorembox
			GLOBAL	gemsreadmbox
			GLOBAL	gemssamprate
			      	
			GLOBAL	patchbank
			GLOBAL	envbank
			GLOBAL	seqbank
			GLOBAL	sampbank
						
			GLOBAL	BUSREQ
			GLOBAL	BUSRES
			GLOBAL	Z80RAM
			GLOBAL	Z80DMABLOCK
			GLOBAL	Z80DMAUNSAFE
			GLOBAL	Z80MBOXBASE
				
				
				
				
				
				
				
				
				
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
