@echo GOLIATH ANIMATION CONVERTION ...

rem ** CHOP the animations **
call spr gg0101 %1 %2
call spr gg0102 %1 %2
call spr gg0103a %1 %2
call spr gg0103b %1 %2
call spr gg0103c %1 %2
call spr gg0104 %1 %2
call spr gg0105 %1 %2
call spr gg0106 %1 %2
call spr gg0107 %1 %2
call spr gg0108 %1 %2
call spr gg0109 %1 %2
call spr gg0110 %1 %2
call spr gg0111 %1 %2
call spr gg0115 %1 %2
call spr gg0116 %1 %2
call spr gg0117 %1 %2
call spr gg0118 %1 %2
call spr gg0119 %1 %2
call spr gg0120 %1 %2
call spr gg0121 %1 %2
call spr gg0122 %1 %2
call spr gg0123 %1 %2
call spr gg0124 %1 %2
call spr gg0125 %1 %2
call spr gg0126 %1 %2
call spr gg0127 %1 %2
call spr gg0128 %1 %2
call spr gg0129 %1 %2
call spr gg0130 %1 %2
call spr gg0131 %1 %2
call spr gg0132 %1 %2
call spr gg0133 %1 %2
call spr gg0134 %1 %2
call spr gg0150 %1 %2
call spr gg0151 %1 %2
call spr gg0152 %1 %2
call spr gg0154 %1 %2
call spr gg0155 %1 %2
call spr gg0177 %1 %2
call spr gg0182 %1 %2
call spr gg0183 %1 %2
call spr gg0184 %1 %2
call spr gg0185 %1 %2
call spr gg0186 %1 %2
call spr gg0187 %1 %2
call spr gg0188 %1 %2
call spr gg0189 %1 %2
call spr gg0190 %1 %2
call spr gg0191 %1 %2
call spr gg_death %1 %2

rem ** COLLECT the animations **
call col gg0101 
call col gg0102 
call col gg0103a
call col gg0103b
call col gg0103c
call col gg0104 
call col gg0105 
call col gg0106 
call col gg0107 
call col gg0108 
call col gg0109 
call col gg0110 
call col gg0111 
call col gg0115 
call col gg0116 
call col gg0117 
call col gg0118 
call col gg0119 
call col gg0120 
call col gg0121 
call col gg0122 
call col gg0123 
call col gg0124 
call col gg0125 
call col gg0126 
call col gg0127 
call col gg0128 
call col gg0129 
call col gg0130 
call col gg0131 
call col gg0132 
call col gg0133 
call col gg0134 
call col gg0150 
call col gg0151 
call col gg0152 
call col gg0154 
call col gg0155 
call col gg0177 
call col gg0182 
call col gg0183 
call col gg0184 
call col gg0185 
call col gg0186 
call col gg0187 
call col gg0188 
call col gg0189 
call col gg0190 
call col gg0191 
call col gg_death

call modany2

