	dc.b	126		; number of sequences is 126
	dc.b	'ARROW FALL'	; name of sequence 0
	dc.b	'FLAMING ROCK'	; name of sequence 1
	dc.b	'IRIS OPEN'	; name of sequence 2
	dc.b	'IRIS CLOSE'	; name of sequence 3
	dc.b	'POWER UP'	; name of sequence 4
	dc.b	'GOLIATH WING FLAP .FM'	; name of sequence 5
	dc.b	'SMASH WOOD DOOR'	; name of sequence 6
	dc.b	'ROBOT FOOTSTEP'	; name of sequence 7
	dc.b	'HOUND OF HELL'	; name of sequence 8
	dc.b	'ROBOT TRACKING 1'	; name of sequence 9
	dc.b	'ROBOT TRACKING 2'	; name of sequence 10
	dc.b	'BIG THING FLING'	; name of sequence 11
	dc.b	'CABLE SNAPPER'	; name of sequence 12
	dc.b	'PLATFORM MOVEMENT .MBOX'	; name of sequence 13
	dc.b	'ELECTRICITY SURGE'	; name of sequence 14
	dc.b	'GOLIATH BURP'	; name of sequence 15
	dc.b	'GOLIATH DAMAGE'	; name of sequence 16
	dc.b	'GOLIATH DEATH'	; name of sequence 17
	dc.b	'GOLIATH WING FLAP .SMP'	; name of sequence 18
	dc.b	'GOLIATH DIVE'	; name of sequence 19
	dc.b	'VIKING GRUNT'	; name of sequence 20
	dc.b	'GOLIATH SWING'	; name of sequence 21
	dc.b	'GOLIATH THROW'	; name of sequence 22
	dc.b	'VALKYRIE DAMAGE'	; name of sequence 23
	dc.b	'ROBOT SCREAM'	; name of sequence 24
	dc.b	'ROBOT WALK'	; name of sequence 25
	dc.b	'FIRE JETS'	; name of sequence 26
	dc.b	'BIG ROCKS FALLING '	; name of sequence 27
	dc.b	'SMALL ROCKS FALLING'	; name of sequence 28
	dc.b	'METAL HIT'	; name of sequence 29
	dc.b	'LIGHTNING'	; name of sequence 30
	dc.b	'CASTLE BOSS DISAPPEAR'	; name of sequence 31
	dc.b	'THROW AXE'	; name of sequence 32
	dc.b	'SWING AXE'	; name of sequence 33
	dc.b	'WALL SMASH'	; name of sequence 34
	dc.b	'FLAMING LOGS'	; name of sequence 35
	dc.b	'CHAINS'	; name of sequence 36
	dc.b	'CRUMBLING ROCKS'	; name of sequence 37
	dc.b	'CLIMBING WALL'	; name of sequence 38
	dc.b	'SLIDING DOWN WALL'	; name of sequence 39
	dc.b	'MORNING STAR&CHAIN'	; name of sequence 40
	dc.b	'CAULDRON SPITS'	; name of sequence 41
	dc.b	'CAULDRON SPITS 2'	; name of sequence 42
	dc.b	'CAULDRON SPITS 3'	; name of sequence 43
	dc.b	'VIKING SCREAM'	; name of sequence 44
	dc.b	'VIKING DEATH'	; name of sequence 45
	dc.b	'LASER'	; name of sequence 46
	dc.b	'LASER BLAST 2'	; name of sequence 47
	dc.b	'WHIP 1ST'	; name of sequence 48
	dc.b	'GLASS'	; name of sequence 49
	dc.b	'EXPLOSION'	; name of sequence 50
	dc.b	'ROOKERY CLAW OPEN'	; name of sequence 51
	dc.b	'ROOKERY CLAW CLOSE'	; name of sequence 52
	dc.b	'OIL SPILLS'	; name of sequence 53
	dc.b	'OIL SPLATS'	; name of sequence 54
	dc.b	'CIRCLING CIRCLE'	; name of sequence 55
	dc.b	'METAL RODS'	; name of sequence 56
	dc.b	'EXPLOSION FM'	; name of sequence 57
	dc.b	'GOLIATH LANDS'	; name of sequence 58
	dc.b	'GOLIATH TUMBLE'	; name of sequence 59
	dc.b	'CASTLE 1'	; name of sequence 60
	dc.b	'CASTLE 2'	; name of sequence 61
	dc.b	'ROOKERY 1'	; name of sequence 62
	dc.b	'ROOKERY 2'	; name of sequence 63
	dc.b	'THE SUBWAY'	; name of sequence 64
	dc.b	'TITLE THEME'	; name of sequence 65
	dc.b	'MUSEUM'	; name of sequence 66
	dc.b	'STORY SCREEN'	; name of sequence 67
	dc.b	'THE FORGE'	; name of sequence 68
	dc.b	'BOSS MUSIC'	; name of sequence 69
	dc.b	'GAME OVER'	; name of sequence 70
	dc.b	'THE HAMMER'	; name of sequence 71
	dc.b	'REAL SCREEN MUSIC'	; name of sequence 72
	dc.b	'TECHNO'	; name of sequence 73
	dc.b	'<UNUSED #74>'	; name of sequence 74
	dc.b	'<UNUSED #75>'	; name of sequence 75
	dc.b	'<UNUSED #76>'	; name of sequence 76
	dc.b	'<UNUSED #77>'	; name of sequence 77
	dc.b	'<UNUSED #78>'	; name of sequence 78
	dc.b	'BLOB'	; name of sequence 79
	dc.b	'ELEVATOR SURGE?'	; name of sequence 80
	dc.b	'PAUSE'	; name of sequence 81
	dc.b	'ROOKERY FLAME'	; name of sequence 82
	dc.b	'ELECTRONIC ZAP 1'	; name of sequence 83
	dc.b	'SOME KIND OF ROBOT NOIS'	; name of sequence 84
	dc.b	'ROCKET PUNCH'	; name of sequence 85
	dc.b	'ENERGIZER'	; name of sequence 86
	dc.b	'FIRE HYDRANT'	; name of sequence 87
	dc.b	'ROBOT LEAP'	; name of sequence 88
	dc.b	'CHIME 1'	; name of sequence 89
	dc.b	'GOLIATH DAMAGE 1'	; name of sequence 90
	dc.b	'GOLIATH DAMAGE 2'	; name of sequence 91
	dc.b	'GOLIATH DAMAGE 3'	; name of sequence 92
	dc.b	'ELECTRIC ELEVATOR'	; name of sequence 93
	dc.b	'CHIME'	; name of sequence 94
	dc.b	'EXPLOSION 1'	; name of sequence 95
	dc.b	'EXPLOSION 2'	; name of sequence 96
	dc.b	'EXPLOSION 3'	; name of sequence 97
	dc.b	'EXPLOSION LOOP'	; name of sequence 98
	dc.b	'FEMALE SCREAM'	; name of sequence 99
	dc.b	'GOLIATH ROAR'	; name of sequence 100
	dc.b	'GREEN ENERGY BALL'	; name of sequence 101
	dc.b	'SUBWAY HORN'	; name of sequence 102
	dc.b	'LAND SFX'	; name of sequence 103
	dc.b	'METAL CLANG 1'	; name of sequence 104
	dc.b	'ROOK CLAW CLOSE'	; name of sequence 105
	dc.b	'ROOK CLAW OPEN'	; name of sequence 106
	dc.b	'METAL CLANG 2'	; name of sequence 107
	dc.b	'ROBOT START'	; name of sequence 108
	dc.b	'SEGA!!!'	; name of sequence 109
	dc.b	'SMALL LASER BLAST'	; name of sequence 110
	dc.b	'SUBWAY CLANG'	; name of sequence 111
	dc.b	'ARROW 1'	; name of sequence 112
	dc.b	'GOLIATH SWIPE #2'	; name of sequence 113
	dc.b	'VENT OPEN/CLOSE'	; name of sequence 114
	dc.b	'GOLIATH SWIPE 3'	; name of sequence 115
	dc.b	'GOLIATH SWIPE 4'	; name of sequence 116
	dc.b	'EVIL SCREAM'	; name of sequence 117
	dc.b	'WHIP 2ND'	; name of sequence 118
	dc.b	'GOLIATH ROAR'	; name of sequence 119
	dc.b	'BRONX GROWL'	; name of sequence 120
	dc.b	'GATE OPEN FAST'	; name of sequence 121
	dc.b	'GATE CLOSE FAST'	; name of sequence 122
	dc.b	'LOW FREQ RUMBLE'	; name of sequence 123
	dc.b	'SUBTLE FLAMES'	; name of sequence 124
	dc.b	'CASTLE BOSS APPEAR'	; name of sequence 125
